### PR TITLE
 Added two new sections under Explanation

### PR DESCRIPTION
**Pull request by steveraysteveray**
@gtfierro, hopefully I did this right. I updated the _toc.yml as well.

### CODE REVIEW

**Review by MatthewSteen — COMMENTED** [review]
A couple comments...

1. Rename `closed_world.md` to `closed_world_assumption.md` to match heading1. 
2. Move `units_of_measure.md` to `reference/units_of_measure.md` since it's information-oriented. 
    It could also be added to one of the _existing_ files in `reference`.

**Comment by gtfierro** [comment]
Made those changes @MatthewSteen . Is there anything else you wanted to add to the PR, @steveraysteveray ?

**Comment by steveraysteveray** [comment]
@gtfierro, yes, I will be updating the closed world explanation file today to reflect the suggestions made on Friday's meeting. Please stay tuned.

**Comment by steveraysteveray** [comment]
@gtfierro, I am a little unsure about file management though. Should I be merging the gh-pages branch into srr-explanations before proceeding, so that it picks up the renaming and shuffling of files?

**Comment by MatthewSteen** [comment]
> @gtfierro, I am a little unsure about file management though. Should I be merging the gh-pages branch into srr-explanations before proceeding, so that it picks up the renaming and shuffling of files?

No, the `gh-pages` branch is deployed automatically. The `book.yml` GitHub action deploys on pull requests so all these changes are live (which we should probably change in the future).

**Comment by steveraysteveray** [comment]
Never mind! I just did a pull of srr-explanations, and it now reflects the changes you all made. I'll start from there.

**Review by MatthewSteen — APPROVED** [review]

**Comment by steveraysteveray** [comment]
@gtfierro, should I just merge this, or do you want to do the merges?

**Comment by gtfierro** [comment]
I'll merge this one, but in the future, go ahead and merge once its ready!

**Pull request merged**
