### PR TITLE
Working on examples pages

### PR DESCRIPTION
**Pull request by gtfierro**
@MatthewSteen @lazlop @pdelgosha22 @wehuang16 feel free to tag others too

Here's an example of what it looks like now. If you like the look of it I can document the workflow. Essentially, you need a .ttl file in _static/models with the same name as an examples/xyz.md file. The xyz.md file needs a section called "## Model Components". The "build_examples.sh" script generates a .jsonld version of each .ttl file and then updates the model components section. The links in the section go to the corresponding explore.open223.info pages

Screenshot 2023-12-12 at 11 19 18 PM

### CODE REVIEW

**Comment by lazlop** [comment]
Cool! This looks good.

I think we may want to add some additional description of the model, essentially just pulling from the slides we presented a while ago, describing the basic system composition and architecture.

**Comment by gtfierro** [comment]
@lazlop absolutely! I couldn't find where those slides were that described the models, but that would definitely go here. As would the screenshot of the G36 system for those models

Having a `models.open223` or an `examples.open223` was the original plan but I was curious how well it would fit here so we didn't have to set up another site (and go through the trouble of setting up that frontend)

The models in `query.open223.info` are copied directly from the `data/` folder of the 223P repo as part of the site build process. I just augmented that process to bring the models here as well, though there will necessarily be some "manual" setup because of the extra metadata we want to capture about these models.

One idea I had here was to add links from the model example page to query.open223.info that capture some common queries on the models. That way you can just click and see the query running.

**Comment by MatthewSteen** [comment]
I really like the model summary table. Could the .sh and .py scripts be run by an action?

Suggest the following for the table headers...

Parent Class | Class | Instances
:- | :- | :-
dad | son | 2

**Comment by gtfierro** [comment]
> I really like the model summary table. Could the .sh and .py scripts be run by an action?
> 
> Suggest the following for the table headers...
> 
> Parent Class	Class	Instances
> dad	son	2

Totally! I'll put those into an action. I like the proposed table header names too

**Comment by gtfierro** [comment]
This is moving into the models.open223.info repo

**Pull request closed without merging**
